### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by iliyaM** [Way2CU/Brinks-Safe-Site#1]
Missing information on Brinks Safe landing page:

- [ ] Clients email to receive emails;
- [ ] Clients domain;
- [ ] Site title. just now it says 'Brinks' in English. if you want something else please give information.

**Comment by talovdat** [comment]
email address in Iliya and Mladen's inbox.

Site title : ברינקס - פתרונות פריטה וניהול מזומנים לעסקים

Domain isn't relevant at this point since the client insist on hosting the site.
Waiting for a list from Mladen about what he needs so he can wright a proper deployment script. 

_Sent from my Samsung SM-J710F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
